-- U_INFO
-- DROP TABLE `U_INFO` CASCADE ;

CREATE  TABLE `U_INFO` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `NAME` VARCHAR(45) NOT NULL ,

  `ID` VARCHAR(45) NOT NULL ,

  `NIC` VARCHAR(45) NOT NULL ,

  `PASSWORD` VARCHAR(45) NOT NULL ,

  `EMAIL` VARCHAR(200) NULL ,

  `POINT` INT NULL ,

  `TYPE_CODE` VARCHAR(5) NULL DEFAULT 'P' ,

  `STATUS_CODE` VARCHAR(5) NULL DEFAULT 'W' ,

  `SERVICE_CODE` VARCHAR(45) NULL,

  `REG_DATETIME` DATETIME NULL ,

  `APPROVE_DATETIME` DATETIME NULL ,

  `APPROVAL_USER_SEQ_ID` BIGINT NULL ,

  PRIMARY KEY (`SEQ_ID`) ,

  UNIQUE INDEX `U_INFO_ID` (`ID` ASC),
  
  UNIQUE INDEX `U_INFO_NIC` (`NIC` ASC) );


-- U_PAYMENT_MASTER
-- DROP TABLE `U_PAYMENT_MASTER` CASCADE ;

CREATE  TABLE `U_PAYMENT_MASTER` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NOT NULL ,

  `USER_NAME` VARCHAR(45) NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `USER_NIC` VARCHAR(45) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_USER_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_PHONE` VARCHAR(45) NULL ,
  
  `FACILITY_ADDRESS` VARCHAR(4000) NULL ,
  
  `FACILITY_HOME_PAGE` VARCHAR(4000) NULL ,
  
  `FACILITY_INTRODUCE` VARCHAR(4000) NULL ,
  
  `FACILITY_CATEGORY` VARCHAR(45) NOT NULL ,

  `FACILITY_REGION` VARCHAR(45) NOT NULL ,

  `TOTAL_PAYMENT_AMOUNT` BIGINT NULL ,
  
  `TOTAL_PAYMENT_NUMBER` INT NULL ,
  
  `PAYMENT_STATUS` VARCHAR(45) NOT NULL ,
  
  `BANNER_TYPE_CODE` VARCHAR(45) NOT NULL ,
  
  `START_DATETIME` DATETIME NOT NULL ,

  `END_DATETIME` DATETIME NOT NULL ,

  `MAIN_BANNER_FILE_NAME` VARCHAR(1000) NULL ,

  `MAIN_BANNER_WEB_LINK` VARCHAR(1000) NULL ,

  `CENTER_BANNER_FILE_NAME` VARCHAR(1000) NULL ,

  `CENTER_BANNER_WEB_LINK` VARCHAR(1000) NULL ,

  `P_FILE_NAME` VARCHAR(1000) NULL ,

  `L_FILE_NAME` VARCHAR(1000) NULL ,

  `THUMBNAIL_FILE_NAME` VARCHAR(1000) NULL ,

  PRIMARY KEY (`SEQ_ID`), 
  
  INDEX `U_PAYMENT_MASTER_USER_SEQ_ID` (`USER_SEQ_ID` ASC),
  
  INDEX `U_PAYMENT_MASTER_USER_ID` (`USER_ID` ASC),
  
  INDEX `U_PAYMENT_MASTER_USER_NIC` (`USER_NIC` ASC) );
  

-- U_PAYMENT_LOG
-- DROP TABLE `U_PAYMENT_LOG` CASCADE ;

CREATE  TABLE `U_PAYMENT_LOG` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NOT NULL ,

  `USER_NAME` VARCHAR(45) NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `USER_NIC` VARCHAR(45) NULL ,

  `FACILITY_CATEGORY` VARCHAR(45) NOT NULL ,

  `PAYMENT_AMOUNT` BIGINT NULL ,
  
  `PAYMENT_DAY_QUANTITY` INT NULL ,
  
  `PAYMENT_TYPE_CODE` VARCHAR(45) NULL ,
  
  `PAYMENT_DESC` TEXT NULL ,
  
  `START_DATETIME` DATETIME NOT NULL ,

  `END_DATETIME` DATETIME NOT NULL ,

  `REGISTER_DATETIME` DATETIME NOT NULL ,

  `REGISTER_USER_SEQ_ID` BIGINT NOT NULL ,

  `REGISTER_IP` VARCHAR(45) NOT NULL ,

  PRIMARY KEY (`SEQ_ID`) ,

  INDEX `U_PAYMENT_LOG_USER_SEQ_ID` (`USER_SEQ_ID` ASC),
  
  INDEX `U_PAYMENT_LOG_USER_ID` (`USER_ID` ASC),
  
  INDEX `U_PAYMENT_LOG_USER_NIC` (`USER_NIC` ASC) );
  

-- U_LOGIN_INFO
-- DROP TABLE `U_LOGIN_INFO` CASCADE ;

CREATE  TABLE `U_LOGIN_INFO` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NOT NULL ,

  `LOGIN_DATETIME` DATETIME NOT NULL ,

  `LOGIN_IP` VARCHAR(45) NOT NULL ,
	
	INDEX `IDX_U_LOGIN_INFO_USEQ_SEQ_ID` (`USER_SEQ_ID` ASC),
	
	INDEX `IDX_U_LIGIN_INFO_LOGIN_IP` (`LOGIN_IP` ASC),
	
  PRIMARY KEY (`SEQ_ID`) )

COMMENT = '회원 로그인 정보';



-- U_ACTION_INFO
-- DROP TABLE `U_ACTION_INFO` CASCADE ;

CREATE  TABLE `U_ACTION_INFO` (

	`SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

	`USER_SEQ_ID` BIGINT NOT NULL ,
  
	`USER_ID` VARCHAR(255) ,
  
	`USER_NIC` VARCHAR(255) ,
	
	`REQ_URI` VARCHAR(255) ,
  
	`CATEGORY` VARCHAR(45) NOT NULL ,
	
	`ACTION_TYPE` VARCHAR(45) NOT NULL ,
	
	`ACTION_SEQ_ID` BIGINT NOT NULL ,
	
	`ACTION_POINT` VARCHAR(45) NOT NULL ,
	
	`ACTION_DATETIME` DATETIME NOT NULL ,

	`ACTION_IP` VARCHAR(45) NOT NULL ,
	
	INDEX `IDX_U_ACTION_INFO_USER_SEQ_ID` (`USER_SEQ_ID` ASC),
	
	INDEX `IDX_U_ACTION_INFO_USER_ID` (`USER_ID` ASC),
	
	INDEX `IDX_U_ACTION_INFO_USER_NIC` (`USER_NIC` ASC),
	
	INDEX `IDX_U_ACTION_INFO_CATEGORY` (`CATEGORY` ASC),
	
	INDEX `IDX_U_ACTION_INFO_ACTION_IP` (`ACTION_IP` ASC),
	
  PRIMARY KEY (`SEQ_ID`) )

COMMENT = '회원 활동 정보';


-- U_CLASS_INFO
-- DROP TABLE `U_CLASS_INFO` CASCADE ;

CREATE  TABLE `U_CLASS_INFO` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `CLASS_POINT` BIGINT NOT NULL ,

  `CLASS_ID` VARCHAR(45) NOT NULL ,

  `CLASS_TYPE_CODE` VARCHAR(45) NOT NULL ,

  `CLASS_IMG_PATH` VARCHAR(500) NOT NULL ,

  PRIMARY KEY (`SEQ_ID`)
  
  )

COMMENT = '회원 계급 정보';  


-- U_QUICK_LINK
-- DROP TABLE `U_QUICK_LINK` CASCADE ;
CREATE  TABLE `U_QUICK_LINK` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NOT NULL ,

  `ORDER_SEQ` BIGINT,

  `QUICK_LINK_NAME` VARCHAR(500) NOT NULL,

  `QUICK_LINK_URL` VARCHAR(500) NOT NULL,

  `WRITE_DATETIME` DATETIME NOT NULL ,

  INDEX `IDX_U_QUICK_LINK_USEQ_SEQ_ID` (`USER_SEQ_ID` ASC),
	
  PRIMARY KEY (`SEQ_ID`) )

COMMENT = '회원 퀵링크 정보';


-- T_POINT_MASTER
-- DROP TABLE `T_POINT_MASTER` CASCADE ;
CREATE  TABLE `T_POINT_MASTER` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `ACTION_TYPE` VARCHAR(45) NOT NULL ,

  `USER_TYPE` VARCHAR(45) NOT NULL ,

  `POINT` BIGINT NOT NULL, 

  PRIMARY KEY (`SEQ_ID`),

  UNIQUE INDEX `U_CLASS_INFO_CLASS_ACTION_CODE` (`CATEGORY`, `ACTION_TYPE`, `USER_TYPE` ASC) )

COMMENT = '포인트 마스터 정보';  

-- T_MENU
-- DROP TABLE `T_MENU` CASCADE ;

CREATE  TABLE `T_MENU` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `MENU_ID` VARCHAR(15) NOT NULL ,

  `MENU_LVL` VARCHAR(1) NOT NULL ,

  `MENU_NM` VARCHAR(100) NOT NULL ,

  `PARMENU_ID` VARCHAR(30) NOT NULL ,

  `FSTIMGPATH` VARCHAR(100) NULL ,

  `WEB_LINK` VARCHAR(100) NULL ,
	
	`DISPLAYSEQ` VARCHAR(3) NULL ,
	
  `DOC_NM` VARCHAR(35) NULL ,

  `USEYN` VARCHAR(1) NULL ,

  `ALLOWED_UTYPE` VARCHAR(10) NULL ,

  `MENU_TYPE` VARCHAR(5) NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,

  UNIQUE INDEX `IDX_T_MENU_SEQ_ID` (`SEQ_ID` ASC),

  UNIQUE INDEX `IDX_T_MENU_MENU_ID` (`MENU_ID` ASC) );


-- T_MENU_ALLOC
-- DROP TABLE `T_MENU_ALLOC` CASCADE ;

CREATE  TABLE `T_MENU_ALLOC` (

  `USER_SEQ_ID` BIGINT NOT NULL ,

  `MENU_ID` VARCHAR(15) NOT NULL ,

  PRIMARY KEY (`USER_SEQ_ID`, `MENU_ID`) )

COMMENT = '메뉴 사용권한';


-- T_MENU_ALLOC_TYPE
-- DROP TABLE `T_MENU_ALLOC_TYPE` CASCADE ;

CREATE  TABLE `T_MENU_ALLOC_TYPE` (

  `TYPE_CODE` VARCHAR(45) NOT NULL ,

  `MENU_ID` VARCHAR(45) NOT NULL ,

  `AUTH_TYPE` VARCHAR(45) NOT NULL ,

  PRIMARY KEY (`TYPE_CODE`, `MENU_ID`, `AUTH_TYPE`) )

COMMENT = '기본메뉴 할당';


-- T_BOARD_FEEDBACK_LOG
-- DROP TABLE `T_BOARD_FEEDBACK_LOG` CASCADE;
CREATE  TABLE `T_BOARD_FEEDBACK_LOG` (

  `USER_SEQ_ID` BIGINT NOT NULL ,

  `BOARD_SEQ_ID` VARCHAR(45) NOT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `IS_RECOMMEND` VARCHAR(45) NOT NULL ,

  `IS_REJECT` VARCHAR(45) NOT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `USER_NIC` VARCHAR(45) NULL ,

  PRIMARY KEY (`USER_SEQ_ID`, `BOARD_SEQ_ID`, `CATEGORY`, `IS_RECOMMEND`, `IS_REJECT`) );



-- T_BOARD_BLACK
-- DROP TABLE `T_BOARD_BLACK` CASCADE;

CREATE  TABLE `T_BOARD_BLACK` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `USER_NIC` VARCHAR(45) NULL ,

  `BLACK_USER_NIC` VARCHAR(45) NULL ,

  `BLACK_USER_PHONE` VARCHAR(45) NULL ,

  `BLACK_USER_PHONE1` VARCHAR(5) NULL ,

  `BLACK_USER_PHONE2` VARCHAR(5) NULL ,

  `BLACK_USER_PHONE3` VARCHAR(5) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `TITLE` VARCHAR(500) NULL ,

  `CONTENT` TEXT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `TARGET_CATEGORY` VARCHAR(45) NOT NULL ,

  `REGION` VARCHAR(45) NULL ,

  `HIT` INT NULL ,

  `RECOMMEND` INT NULL ,

  `REJECT` INT NULL ,

  `SECRET_YN` VARCHAR(1) NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,

  INDEX `IDX_T_BOARD_BLACK_SEQ_ID` (`SEQ_ID` ASC) ,
  
  INDEX `IDX_T_BOARD_BLACK_TARGET_CATEGORY` (`TARGET_CATEGORY` ASC) ,
  
  INDEX `BLACK_USER_PHONE` (`BLACK_USER_PHONE` ASC) ,
  
  INDEX `IDX_T_BOARD_BLACK_BLACK_USER_NIC` (`BLACK_USER_NIC` ASC))

COMMENT = '블랙게시판';


-- T_BOARD_ATTACHMENT
-- DROP TABLE `T_BOARD_ATTACHMENT` CASCADE;

CREATE  TABLE `T_BOARD_ATTACHMENT` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `TABLE_NAME` VARCHAR(45) NULL ,

  `TABLE_SEQ_ID` BIGINT NULL ,

  `P_FILE_NAME` VARCHAR(255) NULL ,

  `L_FILE_NAME` VARCHAR(255) NULL ,

  `THUMBNAIL_FILE_NAME` VARCHAR(255) NULL ,

  `FILE_EXT` VARCHAR(50) NOT NULL ,

  `FILE_SIZE` INT NULL ,

  `DEL_YN` VARCHAR(1) NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
    
  INDEX `IDX_T_BOARD_ATTACHMENT_SEQ_ID` (`SEQ_ID` ASC))

COMMENT = '첨부파일';


-- DROP TABLE `T_BOARD_REPLY` CASCADE;

CREATE  TABLE `T_BOARD_REPLY` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `TABLE_NAME` VARCHAR(45) NULL ,

  `ROOT_SEQ_ID` BIGINT NULL ,

  `REPLY_ORDER_ID` VARCHAR(45) NOT NULL ,

  `PARENT_SEQ_ID` BIGINT NULL ,

  `REPLY_DEPTH` VARCHAR(3) NULL ,

  `USER_SEQ_ID` BIGINT NOT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `USER_NIC` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NOT NULL ,

  `CONTENT` TEXT NULL ,
  
  `FILE_SIZE` INT NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,
	
  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
  
  INDEX `IDX_T_BOARD_REPLY_SEQ_ID` (`SEQ_ID` ASC),
   
  UNIQUE INDEX `IDX_T_BOARD_REPLY_KEY` (`TABLE_NAME` ASC, `ROOT_SEQ_ID` ASC, `REPLY_ORDER_ID` ASC)
   
  )

COMMENT = '덧글';


-- T_BOARD_NOTICE
-- DROP TABLE `T_BOARD_NOTICE` CASCADE;

CREATE  TABLE `T_BOARD_NOTICE` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_USER_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_PHONE` VARCHAR(45) NULL ,
  
  `FACILITY_ADDRESS` VARCHAR(500) NULL ,
  
  `FACILITY_HOME_PAGE` VARCHAR(500) NULL ,
  
  `VISIT_TIME` VARCHAR(45) NULL ,
  
  `WAITERESS_NAME` VARCHAR(45) NULL ,
  
  `CONTENT` TEXT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `TARGET_CATEGORY` VARCHAR(45) NOT NULL ,
  
  `REGION` VARCHAR(45) NULL ,

  `HIT` INT NULL ,

  `RECOMMEND` INT NULL ,

  `REJECT` INT NULL ,

  `SECRET_YN` VARCHAR(1) NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
  
  INDEX `IDX_T_BOARD_NOTICE_TARGET_CATEGORY` (`TARGET_CATEGORY` ASC) ,
  
  INDEX `IDX_T_BOARD_NOTICE_USER_SEQ_ID` (`USER_SEQ_ID` ASC))

COMMENT = '공지사항';


-- T_BOARD_BUSINESS_INFO
-- DROP TABLE `T_BOARD_BUSINESS_INFO` CASCADE;

CREATE  TABLE `T_BOARD_BUSINESS_INFO` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_USER_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_PHONE` VARCHAR(45) NULL ,
  
  `FACILITY_ADDRESS` VARCHAR(500) NULL ,
  
  `FACILITY_HOME_PAGE` VARCHAR(500) NULL ,
  
  `VISIT_TIME` VARCHAR(45) NULL ,
  
  `WAITERESS_NAME` VARCHAR(45) NULL ,
  
  `CONTENT` TEXT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `TARGET_CATEGORY` VARCHAR(45) NOT NULL ,
  
  `REGION` VARCHAR(45) NULL ,

  `HIT` INT NULL ,

  `RECOMMEND` INT NULL ,

  `REJECT` INT NULL ,

  `SECRET_YN` VARCHAR(1) NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
  
  INDEX `IDX_T_BOARD_BUSINESS_INFO_TARGET_CATEGORY` (`TARGET_CATEGORY` ASC) ,

  INDEX `IDX_T_BOARD_BUSINESS_INFO_USER_SEQ_ID` (`USER_SEQ_ID` ASC))

COMMENT = '업소정보';


-- T_BOARD_LINE_UP
-- DROP TABLE `T_BOARD_LINE_UP` CASCADE;

CREATE  TABLE `T_BOARD_LINE_UP` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_USER_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_PHONE` VARCHAR(45) NULL ,
  
  `FACILITY_ADDRESS` VARCHAR(500) NULL ,
  
  `FACILITY_HOME_PAGE` VARCHAR(500) NULL ,
  
  `VISIT_TIME` VARCHAR(45) NULL ,
  
  `WAITERESS_NAME` VARCHAR(45) NULL ,
  
  `CONTENT` TEXT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `TARGET_CATEGORY` VARCHAR(45) NOT NULL ,
  
  `REGION` VARCHAR(45) NULL ,

  `HIT` INT NULL ,

  `RECOMMEND` INT NULL ,

  `REJECT` INT NULL ,

  `SECRET_YN` VARCHAR(1) NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
  
  INDEX `IDX_T_BOARD_LINE_UP_TARGET_CATEGORY` (`TARGET_CATEGORY` ASC) ,
  
  INDEX `IDX_T_BOARD_LINE_UP_USER_SEQ_ID` (`USER_SEQ_ID` ASC))

COMMENT = '라인업';


-- T_BOARD_POSTSCRIPT
-- DROP TABLE `T_BOARD_POSTSCRIPT` CASCADE;

CREATE  TABLE `T_BOARD_POSTSCRIPT` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_USER_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_PHONE` VARCHAR(45) NULL ,
  
  `FACILITY_ADDRESS` VARCHAR(500) NULL ,
  
  `FACILITY_HOME_PAGE` VARCHAR(500) NULL ,
  
  `VISIT_TIME` VARCHAR(45) NULL ,
  
  `WAITERESS_NAME` VARCHAR(45) NULL ,
  
  `CONTENT` TEXT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `TARGET_CATEGORY` VARCHAR(45) NOT NULL ,
  
  `REGION` VARCHAR(45) NULL ,

  `HIT` INT NULL ,

  `RECOMMEND` INT NULL ,

  `REJECT` INT NULL ,

  `SECRET_YN` VARCHAR(1) NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
  
  INDEX `IDX_T_BOARD_POSTSCRIPT_TARGET_CATEGORY` (`TARGET_CATEGORY` ASC) ,
  
  INDEX `IDX_T_BOARD_POSTSCRIPT_USER_SEQ_ID` (`USER_SEQ_ID` ASC))

COMMENT = '후기';


-- T_BOARD_COMMUNITY
-- DROP TABLE `T_BOARD_COMMUNITY` CASCADE;

CREATE  TABLE `T_BOARD_COMMUNITY` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_USER_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_PHONE` VARCHAR(45) NULL ,
  
  `FACILITY_ADDRESS` VARCHAR(500) NULL ,
  
  `FACILITY_HOME_PAGE` VARCHAR(500) NULL ,
  
  `VISIT_TIME` VARCHAR(45) NULL ,
  
  `WAITERESS_NAME` VARCHAR(45) NULL ,
  
  `CONTENT` TEXT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `TARGET_CATEGORY` VARCHAR(45) NOT NULL ,
  
  `REGION` VARCHAR(45) NULL ,

  `HIT` INT NULL ,

  `RECOMMEND` INT NULL ,

  `REJECT` INT NULL ,

  `SECRET_YN` VARCHAR(1) NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
  
  INDEX `IDX_T_BOARD_COMMUNITY_TARGET_CATEGORY` (`TARGET_CATEGORY` ASC) ,
  
  INDEX `IDX_T_BOARD_COMMUNITY_USER_SEQ_ID` (`USER_SEQ_ID` ASC))

COMMENT = '커뮤니티';


-- T_BOARD_CENTER
-- DROP TABLE `T_BOARD_CENTER` CASCADE;

CREATE  TABLE `T_BOARD_CENTER` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `USER_SEQ_ID` BIGINT NULL ,

  `USER_ID` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `FACILITY_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_USER_NAME` VARCHAR(45) NULL ,
  
  `FACILITY_PHONE` VARCHAR(45) NULL ,
  
  `FACILITY_ADDRESS` VARCHAR(500) NULL ,
  
  `FACILITY_HOME_PAGE` VARCHAR(500) NULL ,
  
  `VISIT_TIME` VARCHAR(45) NULL ,
  
  `WAITERESS_NAME` VARCHAR(45) NULL ,
  
  `CONTENT` TEXT NULL ,

  `CATEGORY` VARCHAR(45) NOT NULL ,

  `TARGET_CATEGORY` VARCHAR(45) NOT NULL ,
  
  `REGION` VARCHAR(45) NULL ,

  `HIT` INT NULL ,

  `RECOMMEND` INT NULL ,

  `REJECT` INT NULL ,

  `SECRET_YN` VARCHAR(1) NULL ,

  `BLIND_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,
  
  INDEX `IDX_T_BOARD_CENTER_TARGET_CATEGORY` (`TARGET_CATEGORY` ASC) ,
  
  INDEX `IDX_T_BOARD_CENTER_USER_SEQ_ID` (`USER_SEQ_ID` ASC))

COMMENT = '화류센터';


-- T_MESSAGE_SEND
-- DROP TABLE `T_MESSAGE_SEND` CASCADE;

CREATE  TABLE `T_MESSAGE_SEND` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `SEND_MESSAGE_SEQ_ID` BIGINT,

  `SND_USER_SEQ_ID` BIGINT NULL ,

  `SND_USER_ID` VARCHAR(45) NULL ,

  `SND_USER_NIC` VARCHAR(45) NULL ,

  `RCV_USER_SEQ_ID` BIGINT NULL ,

  `RCV_USER_ID` VARCHAR(45) NULL ,

  `RCV_USER_NIC` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `CONTENT` TEXT NULL ,

  `RCV_DATETIME` DATETIME NULL ,
  
  `RCV_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,

  INDEX `IDX_T_MESSAGE_SEND_SND_USER_SEQ_ID` (`SND_USER_SEQ_ID` ASC), 
  
  INDEX `IDX_T_MESSAGE_SEND_RCV_USER_SEQ_ID` (`RCV_USER_SEQ_ID` ASC))

COMMENT = '보낸 쪽지';


-- T_MESSAGE_RECEIVED
-- DROP TABLE `T_MESSAGE_RECEIVED` CASCADE;

CREATE  TABLE `T_MESSAGE_RECEIVED` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `SEND_MESSAGE_SEQ_ID` BIGINT,

  `SND_USER_SEQ_ID` BIGINT NULL ,

  `SND_USER_ID` VARCHAR(45) NULL ,

  `SND_USER_NIC` VARCHAR(45) NULL ,

  `RCV_USER_SEQ_ID` BIGINT NULL ,

  `RCV_USER_ID` VARCHAR(45) NULL ,

  `RCV_USER_NIC` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `CONTENT` TEXT NULL ,

  `RCV_DATETIME` DATETIME NULL ,
  
  `RCV_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,

  INDEX `IDX_T_MESSAGE_RECEIVED_SEND_MESSAGE_SEQ_ID` (`SEND_MESSAGE_SEQ_ID` ASC), 
  
  INDEX `IDX_T_MESSAGE_RECEIVED_SND_USER_SEQ_ID` (`SND_USER_SEQ_ID` ASC), 
  
  INDEX `IDX_T_MESSAGE_RECEIVED_RCV_USER_SEQ_ID` (`RCV_USER_SEQ_ID` ASC))

COMMENT = '받은 쪽지';


-- T_MESSAGE_RESERVED
-- DROP TABLE `T_MESSAGE_RESERVED` CASCADE;

CREATE  TABLE `T_MESSAGE_RESERVED` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `SEND_MESSAGE_SEQ_ID` BIGINT,

  `MV_USER_SEQ_ID` BIGINT NULL ,

  `SND_USER_SEQ_ID` BIGINT NULL ,

  `SND_USER_ID` VARCHAR(45) NULL ,

  `SND_USER_NIC` VARCHAR(45) NULL ,

  `RCV_USER_SEQ_ID` BIGINT NULL ,

  `RCV_USER_ID` VARCHAR(45) NULL ,

  `RCV_USER_NIC` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `CONTENT` TEXT NULL ,

  `RCV_DATETIME` DATETIME NULL ,
  
  `RCV_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,

  INDEX `IDX_T_MESSAGE_RESERVED_MV_USER_SEQ_ID` (`MV_USER_SEQ_ID` ASC), 
  
  INDEX `IDX_T_MESSAGE_RESERVED_SND_USER_SEQ_ID` (`SND_USER_SEQ_ID` ASC), 
  
  INDEX `IDX_T_MESSAGE_RESERVED_RCV_USER_SEQ_ID` (`RCV_USER_SEQ_ID` ASC))

COMMENT = '보관 쪽지';


-- T_MESSAGE_DELETED
-- DROP TABLE `T_MESSAGE_DELETED` CASCADE;

CREATE  TABLE `T_MESSAGE_DELETED` (

  `SEQ_ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `SEND_MESSAGE_SEQ_ID` BIGINT,

  `MV_USER_SEQ_ID` BIGINT NULL ,

  `SND_USER_SEQ_ID` BIGINT NULL ,

  `SND_USER_ID` VARCHAR(45) NULL ,

  `SND_USER_NIC` VARCHAR(45) NULL ,

  `RCV_USER_SEQ_ID` BIGINT NULL ,

  `RCV_USER_ID` VARCHAR(45) NULL ,

  `RCV_USER_NIC` VARCHAR(45) NULL ,

  `TITLE` VARCHAR(500) NULL ,

  `CONTENT` TEXT NULL ,

  `RCV_DATETIME` DATETIME NULL ,
  
  `RCV_YN` VARCHAR(1) NULL ,

  `DEL_YN` VARCHAR(1) NULL ,

  `WRITER_IP` VARCHAR(30) NULL ,

  `WRITE_DATETIME` DATETIME NULL ,
  
  PRIMARY KEY (`SEQ_ID`) ,

  INDEX `IDX_T_MESSAGE_DELETED_MV_USER_SEQ_ID` (`MV_USER_SEQ_ID` ASC), 
  
  INDEX `IDX_T_MESSAGE_DELETED_SND_USER_SEQ_ID` (`SND_USER_SEQ_ID` ASC), 
  
  INDEX `IDX_T_MESSAGE_DELETED_RCV_USER_SEQ_ID` (`RCV_USER_SEQ_ID` ASC))

COMMENT = '삭제 쪽지';